name: "multi-event-pipeline"
on:
    push:
        branches:
            - master
            - test

    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "running on master/test push"
              run: echo "running on master/test push"

    on-pull-request:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: "running on pull request"
              run: echo "running on pull request"
    
    on-workflow_dispatch:
        runs-on: ubuntu-latest
        if: github.event_name == 'workflow_dispatch'
        steps:
            - name: "running on workflow dispatch"
              run: echo "running on workflow dispatch"